USE [master]
GO

/****** Object:  Database [dbGym]    Script Date: 9/21/2017 12:20:03 PM ******/
CREATE DATABASE [dbGym]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbGym', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.NADUN\MSSQL\DATA\dbGym.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dbGym_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.NADUN\MSSQL\DATA\dbGym_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [dbGym] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbGym].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbGym] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbGym] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbGym] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbGym] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbGym] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbGym] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dbGym] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbGym] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbGym] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbGym] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbGym] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbGym] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbGym] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbGym] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbGym] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dbGym] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbGym] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbGym] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbGym] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbGym] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbGym] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbGym] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbGym] SET RECOVERY FULL 
GO

ALTER DATABASE [dbGym] SET  MULTI_USER 
GO

ALTER DATABASE [dbGym] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbGym] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbGym] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dbGym] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [dbGym] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [dbGym] SET QUERY_STORE = OFF
GO

USE [dbGym]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [dbGym] SET  READ_WRITE 
GO


